[project]
name = "notateit"
version = "2.0.1"
description = "Notateit Viewer Remake"
authors = [
    { name = "Nikita Denissov", email = "n.denissov@proton.me" }
]
readme = "README.md"
requires-python = ">=3.10,<3.15"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Multimedia :: Graphics :: Viewers",
]

[tool.poetry.dependencies]
pyside6 = "^6.11.1"
pillow = "^12.3.0" # NOT COMPATIBLE WITH PYTHON <3.10: Secure Pillow versions drops python <3.10 support.

[project.urls]
Homepage = "https://github.com/ndenissov/notateit"
Repository = "https://github.com/ndenissov/notateit"

[project.scripts]
notateit = "notateit.__main__:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{ include = "notateit" }]
include = ["notateit/notateit_remake.png"]
